2017/12/14 12:31:55 [error] 6#6: *1 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
PDOException: SQLSTATE[HY000] [1045] Access denied for user 'futuregames'@'172.16.21.195' (using password: YES) in /www/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php:660
Stack trace:
#0 /www/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php(660): PDO->__construct('mysql:host=172....', 'futuregames', 'tKElEaeALRzyfeH...', NULL)
#1 /www/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php(586): yii\db\Connection->createPdoInstance()
#2 /www/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php(943): yii\db\Connection->open()
#3 /www/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php(930): yii\db\Connection->getMasterPdo()
#4 /www/gitee/automation-platform/vendor/yiisoft/yii2/db/Command.php(243): yii\db\Connection->getSlavePdo()
#5 /www/gitee/automation-platform/vendor/yiisoft/yii2/db/Command.php(1062): yii\db\Command->prepare(true)
#6 /www/gitee/automation-platform/vendor/yiisoft/yi" while reading upstream, client: 172.18.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "172.16.21.195"
2017/12/14 12:34:40 [error] 8#8: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "172.16.21.195"
2017/12/14 12:35:39 [error] 5#5: *1 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
PDOException: SQLSTATE[HY000] [1045] Access denied for user 'futuregames'@'172.16.21.195' (using password: YES) in /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php:660
Stack trace:
#0 /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php(660): PDO->__construct('mysql:host=172....', 'futuregames', 'tKElEaeALRzyfeH...', NULL)
#1 /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php(586): yii\db\Connection->createPdoInstance()
#2 /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php(943): yii\db\Connection->open()
#3 /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php(930): yii\db\Connection->getMasterPdo()
#4 /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Command.php(243): yii\db\Connection->getSlavePdo()
#5 /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Command.php(1062): yii\db\Command->prepare(true)
#6 /data/gitee/automation-platform/vendor/yi" while reading upstream, client: 172.18.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "172.16.21.195"
2017/12/14 12:35:50 [error] 5#5: *1 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
PDOException: SQLSTATE[HY000] [1045] Access denied for user 'futuregames'@'172.16.21.195' (using password: YES) in /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php:660
Stack trace:
#0 /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php(660): PDO->__construct('mysql:host=172....', 'futuregames', 'tKElEaeALRzyfeH...', NULL)
#1 /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php(586): yii\db\Connection->createPdoInstance()
#2 /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php(943): yii\db\Connection->open()
#3 /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php(930): yii\db\Connection->getMasterPdo()
#4 /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Command.php(243): yii\db\Connection->getSlavePdo()
#5 /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Command.php(1062): yii\db\Command->prepare(true)
#6 /data/gitee/automation-platform/vendor/yi" while reading upstream, client: 172.18.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "172.16.21.195"
2017/12/14 12:35:53 [error] 5#5: *1 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
PDOException: SQLSTATE[HY000] [1045] Access denied for user 'futuregames'@'172.16.21.195' (using password: YES) in /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php:660
Stack trace:
#0 /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php(660): PDO->__construct('mysql:host=172....', 'futuregames', 'tKElEaeALRzyfeH...', NULL)
#1 /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php(586): yii\db\Connection->createPdoInstance()
#2 /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php(943): yii\db\Connection->open()
#3 /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php(930): yii\db\Connection->getMasterPdo()
#4 /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Command.php(243): yii\db\Connection->getSlavePdo()
#5 /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Command.php(1062): yii\db\Command->prepare(true)
#6 /data/gitee/automation-platform/vendor/yi" while reading upstream, client: 172.18.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "172.16.21.195"
2017/12/14 12:45:51 [error] 5#5: *5 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
PDOException: SQLSTATE[HY000] [1045] Access denied for user 'futuregames'@'172.16.21.195' (using password: YES) in /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php:660
Stack trace:
#0 /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php(660): PDO->__construct('mysql:host=172....', 'futuregames', 'tKElEaeALRzyfeH...', NULL)
#1 /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php(586): yii\db\Connection->createPdoInstance()
#2 /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php(943): yii\db\Connection->open()
#3 /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Connection.php(930): yii\db\Connection->getMasterPdo()
#4 /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Command.php(243): yii\db\Connection->getSlavePdo()
#5 /data/gitee/automation-platform/vendor/yiisoft/yii2/db/Command.php(1062): yii\db\Command->prepare(true)
#6 /data/gitee/automation-platform/vendor/yi" while reading upstream, client: 172.18.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "172.16.21.195"
